//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrsnlTkp.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelBilgi
    {
        public long TcKimlikNo { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<System.DateTime> DogumTarihi { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
        public string Unvan { get; set; }
        public byte[] Resim { get; set; }
    }
}
